---
- hosts: localhost
  vars_files:
    - settings.yml
    - ['~/cloudbox/accounts.yml', '~/cloudbox/defaults/accounts.yml.default']
    - ['~/cloudbox/settings.yml', '~/cloudbox/defaults/settings.yml.default']
    - ['~/cloudbox/adv_settings.yml', '~/cloudbox/defaults/adv_settings.yml.default']
  roles:
    - { role: pre_tasks }
    - { role: magicmirror, tags: ['magicmirror'] }
    - { role: deezloader, tags: ['deezloader'] }
    - { role: autoheal, tags: ['autoheal'] }
    - { role: home-assistant, tags: ['home-assistant'] }
